import { createStore } from "solid-js/store";

const [chessGame, setChessGame] = createStore({
  rows: [
    [
      { tileColor: "light", piece: "tower-dark" },
      { tileColor: "dark", piece: "knight-dark" },
      { tileColor: "light", piece: "bishop-dark" },
      { tileColor: "dark", piece: "queen-dark" },
      { tileColor: "light", piece: "king-dark" },
      { tileColor: "dark", piece: "bishop-dark" },
      { tileColor: "light", piece: "knight-dark" },
      { tileColor: "light", piece: "tower-dark" },
    ],
    [
      { tileColor: "dark", piece: "pawn-dark" },
      { tileColor: "light", piece: "pawn-dark" },
      { tileColor: "dark", piece: "pawn-dark" },
      { tileColor: "light", piece: "pawn-dark" },
      { tileColor: "dark", piece: "pawn-dark" },
      { tileColor: "light", piece: "pawn-dark" },
      { tileColor: "dark", piece: "pawn-dark" },
      { tileColor: "light", piece: "pawn-dark" },
    ],
    [
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
    ],
    [
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
    ],
    [
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark", piece: "pawn-light" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
    ],
    [
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
      { tileColor: "dark" },
      { tileColor: "light" },
    ],
    [
      { tileColor: "light", piece: "pawn-light" },
      { tileColor: "dark", piece: "pawn-light" },
      { tileColor: "light", piece: "pawn-light" },
      { tileColor: "dark", piece: "" },
      { tileColor: "light", piece: "pawn-light" },
      { tileColor: "dark", piece: "pawn-light" },
      { tileColor: "light", piece: "pawn-light" },
      { tileColor: "dark", piece: "pawn-light" },
    ],
    [
      { tileColor: "dark", piece: "tower-light" },
      { tileColor: "light", piece: "knight-light" },
      { tileColor: "dark", piece: "bishop-light" },
      { tileColor: "light", piece: "queen-light" },
      { tileColor: "dark", piece: "king-light" },
      { tileColor: "light", piece: "bishop-light" },
      { tileColor: "dark", piece: "knight-light" },
      { tileColor: "light", piece: "tower-light" },
    ],
  ],
});

export { chessGame, setChessGame };
